### ISSUE TITLE
Adding mod's meta data file

### ISSUE THREAD

**Issue by alan-cugler** [alan-cugler/pymods#3]
Looking at www.nexusmods.com its clear that meta data exists for categorizing the mods but its not easily manipulable. 

Also watching https://www.youtube.com/watch?v=sL_nmaMeuWU on how to decide "load order" for mods. There is some amount of grouping related mods makes it easier to decide load order and notice mod conflicts.

I think studying this problem I would like to add a yaml file containing descriptive meta data for pymods to use in GUI to help the user select and organize those mods for a new profile play through.

Example yaml file:
```YAML
# File:[pymods]/mods/SkyUI.yaml

SkyUI:
  - game: 'skyrim special edition'
  - mod_type: 'user interface'
  - file_type:
      - 'bsa'
      - 'esp'
  - description: |
      Elegant, PC-friendly interface for in-game menus.
```
